FROM node:latest
FROM mongo:latest

ENV PYTH /node_modules/typescript/bin
RUN git clone https://github.com/tdworowy/TypeScriptPlayground.git
WORKDIR  /TypeScriptPlayground/full_stack_example/full_stack_app
RUN npm install
RUN node loadTestData.js
EXPOSE 27017